### ISSUE TITLE
Decide background for homepage

### ISSUE THREAD

**Issue by SaptakS** [GeekHaven/Effervescence-2015#4]
Decide the styling and theme for the homepage. We can stick with pacificrimmovie.com website or can do something else if you have something better in mind.

**Comment by adeora7** [comment]
previous year images as poster was a nice idea unless we come up with something else

**Comment by SaptakS** [comment]
Yes we can do with some series of images...
You can either use a slideshow kind of thing on the background..
or some other relevant effect on the basis of the theme..
