### ISSUE TITLE
Theme?

### ISSUE THREAD

**Issue by ddemented** [GeekHaven/Effervescence-2015#7]
has the theme for effe been decided as bollywood? if not, why not we decide some time to finalise the theme as this doesnt look that great, as our seniors did with effe and aparoskha site?

**Comment by adeora7** [comment]
Yes sir..it has been decided

**Comment by ddemented** [comment]
alright..

**Comment by adeora7** [comment]
Moreover ....we have not yet completed it .... I hope it will look great
