### ISSUE TITLE
Position Img right of menu bar!

### ISSUE THREAD

**Issue by ddemented** [GeekHaven/Effervescence-2015#8]

**Comment by ddemented** [comment]
Do not close an issue without doing it or without a reason ty

**Comment by adeora7** [comment]
Which image are we talking about here ?

**Comment by ddemented** [comment]
Well I can't see the updated website  as am traveling  now and using the phone...  But there was a img  which wasn't positioned properly..  But do not close a thread without  a reason  it's not the way

**Comment by adeora7** [comment]
Ok sir ... Please let us know when u see the updated website

**Comment by SaptakS** [comment]
As you cannot see the website so you must not have seen that the image you are talking about isn't there in the website anymore. Moreover don't create a github issue on design issues when you can pretty well understand from seeing the website that it is not completed. And you can ask for enhancement in a design or feature. Please do not mention what to do with something that isn't there in the website at all.

**Comment by ddemented** [comment]
So u just can't close  the issue  without a reason..  Am pointing  that out.  If these simple things r not followed  it's gonna be hard...  Vivek  closed it without a reason.
