### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vivekanand1101** [GeekHaven/Effervescence-2015#9]
This is not an immediate requirement, and might seem silly to some people. This would be really helpful for the newcomers of our college and also for those who would like to contribute. Although this might seem to be a waste of time but this would be very helpful in changing our  trend - 'competitive coding is everything'.
Docs of few other organisations in github can be helpful.

**Comment by hackerkid** [comment]
Yeah. I wrote a bit here https://github.com/GeekHaven/Getting-Started . Consider adding more to the guidelines.

**Comment by SaptakS** [comment]
Yeah. But I dont think this should be an issue for the effe website. Because as far as I have seen websites dont usually have docs.

**Comment by vivekanand1101** [comment]
This is not about having docs about a website. The EFFE is the face of our college and it's website and it's app will be the face of Geekhaven. By making it more understandable to even the  noobs of web development you are improving it's chances to be improved. Maybe nobody comes this year to contribute, but one thing is for sure - if there is a trend to prepare docs, people will start getting involved slowly year after year. By doing this we are also improving the chances that more and more people are involved in the development work. Also, since this is the first year when the code is on Github, the chances are very high that if we don't prepare docs this time, it will never be prepared - because as you mentioned- it's a website. By not preparing it this time with so much time left, i think we are missing a trick. The rest is of course, up to you and the overall coordinators.
Wouldn't it be an awesome feeling, if as a first year you think - "Ok, this effect is because of this part of the code. This doesn't seem tough".

**Comment by vivekanand1101** [comment]
This is not about having docs about a website. The EFFE is the face of our college and it's website and it's app will be the face of Geekhaven. By making it more understandable to even the  noobs of web development you are improving it's chances to be improved. Maybe nobody comes this year to contribute, but one thing is for sure - if there is a trend to prepare docs, people will start getting involved slowly year after year. By doing this we are also improving the chances that more and more people are involved in the development work. Also, since this is the first year when the code is on Github, the chances are very high that if we don't prepare docs this time, it will never be prepared - because as you mentioned- it's a website. By not preparing it this time with so much time left, i think we are missing a trick. The rest is of course, up to you and the overall coordinators.
Wouldn't it be an awesome feeling, for a first year if they think - "Ok, this effect is because of this part of the code. This doesn't seem tough".

I accidentally closed the issue, sorry about that.

**Comment by SaptakS** [comment]
Yeah I agree with you. Will add the doc as soon as the website reaches a stage where it is suitable for adding a doc

**Comment by SaptakS** [comment]
Done.
